version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "gatsby develop -H 0.0.0.0 -p 8001"
    environment:
      - GATSBY_API_URL=http://127.0.0.1:8000/search
    ports:
      - 8001:8001
    tty: true
    volumes:
      - .:/code
  test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "npm test"
    tty: true
    volumes:
      - .:/code
